<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <!-- Testing helpers and libraries used by unit tests -->
    <PackageReference Include="Moq" Version="4.20.3" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Reference ASP.NET Core shared framework so Microsoft.AspNetCore.* types are available -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <!-- Project references required by the tests -->
    <ProjectReference Include="..\..\src\VianaHub.Global.Gerit.Application\VianaHub.Global.Gerit.Application.csproj" />
    <ProjectReference Include="..\..\src\VianaHub.Global.Gerit.Domain\VianaHub.Global.Gerit.Domain.csproj" />
    <ProjectReference Include="..\..\src\VianaHub.Global.Gerit.Api\VianaHub.Global.Gerit.Api.csproj" />
    <ProjectReference Include="..\..\src\VianaHub.Global.Gerit.Infra.Data\VianaHub.Global.Gerit.Infra.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0" />
  </ItemGroup>

</Project>
